version: '3'
services:
  reverseproxy:
    container_name: reverseproxy-container
    image: nginx:1.17.10
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf   
    ports:
      - "80:80"
      
networks:
  default:
    external:
      name: studart-database-network

